# Include the below for the jekyll theme:

remote_theme: cotes2020/jekyll-theme-chirpy@v5.3.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Just a Random Website
#description: This is the description of the page
show_downloads: false
portal: "https://bangumi.moe"