# Include the below for the jekyll theme:

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: This is the title of the page
description: This is the description of the page
show_downloads: true